def OWNER = 'zahid401'
def REPO_NAME = 'jenkins-cicd-example'
// def IMAGE_NAME = 'helloworld'

def IMAGE_REGISTRY = "${OWNER}/${REPO_NAME}"
def IMAGE_BRANCH_TAG = "${IMAGE_REGISTRY}"

def DOCKER_HOST_VALUE = 'tcp://dind.default:2375'

def DOCKER_POD = """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker:19.03.6
    command:
    - cat
    tty: true
    env:
    - name: DOCKER_HOST
      value: ${DOCKER_HOST_VALUE}
"""

pipeline {
  agent any
  stages {
    stage('Run Docker') {
      agent { kubernetes label: 'docker', yaml: "${DOCKER_POD}" }
      stages {
        stage('Build Docker Image') {
          steps {
            container('docker') {
              sh "docker build -t ${IMAGE_BRANCH_TAG}.${env.GIT_COMMIT[0..6]} ."
            }
          }
        }
      }
    }
  }
}
